services:
  jdk:
    image: openjdk:17-slim-buster
    working_dir: /home/app/spring
    entrypoint: "./mvnw spring-boot:run"
    environment:
      API_PORT: 8081
      API_LOGGING_LEVEL: debug
      API_SHOW_SQL: true
      MARIADB_HOST: db
      MARIADB_PORT: 3306
      MARIADB_USERNAME: api
      MARIADB_PASSWORD: api
      KEYCLOAK_URL: keycloak
      KEYCLOAK_PORT: 8080
      KEYCLOAK_REALM: Spring-DDD
    ports:
      - 8080:8081
    volumes:
      - ${PWD}:/home/app/spring
    networks:
      - tasks_api
    profiles:
        - dev
      
  db:
    environment:
      MARIADB_ROOT_PASSWORD: toor
      MARIADB_USER: api
      MARIADB_PASSWORD: api
      MARIADB_DATABASE: tasks_manager
    profiles:
      - dev
      
  keycloak:
    environment:
        KC_DB_PASSWORD: toor
        KC_HOSTNAME: keycloak # Comment to access into admin by http
        KC_HOSTNAME_PORT: 8080 # Comment to access into admin by http
    profiles:
        - dev