server:
  port: 8080
  servlet:
    context-path: "/api"
    
logging:
  level:
    '[org.springframework.web]': debug

spring:
  datasource:
    url: jdbc:mariadb://${MARIADB_HOST:localhost}:${MARIADB_PORT:3306}/tasks_manager?useSSL=false
    username: ${MARIADB_USERNAME:api}
    password: ${MARIADB_PASSWORD:api}
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    mapping-resources:
     - classpath:com/tasksrest/api/task/infrastructure/jpa_mapping/task.xml
     - classpath:com/tasksrest/api/shared/infrastructure/persistence/jpa_mapping/task_holder.xml
     - classpath:com/tasksrest/api/kanban/infrastructure/persistence/jpa_mapping/kanban.xml
     - classpath:com/tasksrest/api/kanban/infrastructure/persistence/jpa_mapping/columns.xml

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/Spring-DDD
          jwk-set-uri: ${spring.security.oauth2.resourceserver.jwt.issuer-uri}/protocol/openid-connect/certs
    